use broadleaf;

CREATE TABLE broadleaf.ENC_CUSTOMER (
  CUSTOMER_ID bigint(20) NOT NULL,
  PRIMARY KEY (CUSTOMER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE broadleaf.ENC_MEASUREMENTS (
   MEASUREMENT_ID  bigint(20)  NOT NULL,
   MEASUREMENT_NAME VARCHAR(20) NOT NULL,
   MEASUREMENT_DESCRIPTION VARCHAR(200),
   CUSTOMER_ID  bigint(20),
   HEIGHT FLOAT,
   CHEST FLOAT,
   BUST FLOAT,
   DARTLINE FLOAT,
   WAIST FLOAT,
   HIP FLOAT,
   N_WAIST FLOAT,
   SHOULDER FLOAT,
   S_LENGTH FLOAT,
   ARM_HOLE FLOAT,
   T_SLEEVE FLOAT,
   B_SLEEVE FLOAT,
   F_NECK FLOAT,
   B_NECK FLOAT,
   PANT_HEIGHT FLOAT,
   SEAT FLOAT,
   FILLER1 FLOAT,
   FILLER2 FLOAT,
   FILLER3 FLOAT,
   CREATED_BY bigint(20) DEFAULT NULL,
   DATE_CREATED datetime DEFAULT NULL,
   DATE_UPDATED datetime DEFAULT NULL,
   UPDATED_BY bigint(20) DEFAULT NULL,
   END_DATE datetime DEFAULT NULL,
   PRIMARY KEY (MEASUREMENT_ID),
   FOREIGN KEY (CUSTOMER_ID) REFERENCES blc_customer(CUSTOMER_ID)
) ENGINE = InnoDB ROW_FORMAT = DEFAULT;

CREATE INDEX MEASUREMENT_CUSTOMER_INDEX ON enc_measurements (customer_id);


CREATE TABLE  broadleaf.ENC_EXP_MEASUREMENTS (
  EXP_MEASUREMENT_ID bigint(20) NOT NULL,
  EXP_MEASUREMENT_NAME varchar(20) NOT NULL,
  CATEGORY_ID bigint(20) DEFAULT NULL,
  HEIGHT tinyint(4) DEFAULT NULL,
  CHEST tinyint(4) DEFAULT NULL,
  BUST tinyint(4) DEFAULT NULL,
  DARTLINE tinyint(4) DEFAULT NULL,
  WAIST tinyint(4) DEFAULT NULL,
  HIP tinyint(4) DEFAULT NULL,
  N_WAIST tinyint(4) DEFAULT NULL,
  SHOULDER tinyint(4) DEFAULT NULL,
  S_LENGTH tinyint(4) DEFAULT NULL,
  ARM_HOLE tinyint(4) DEFAULT NULL,
  T_SLEEVE tinyint(4) DEFAULT NULL,
  B_SLEEVE tinyint(4) DEFAULT NULL,
  F_NECK tinyint(4) DEFAULT NULL,
  B_NECK tinyint(4) DEFAULT NULL,
  PANT_HEIGHT tinyint(4) DEFAULT NULL,
  SEAT tinyint(4) DEFAULT NULL,
  FILLER1 tinyint(4) DEFAULT NULL,
  FILLER2 tinyint(4) DEFAULT NULL,
  FILLER3 tinyint(4) DEFAULT NULL,
  CREATED_BY bigint(20) DEFAULT NULL,
  DATE_CREATED datetime DEFAULT NULL,
  DATE_UPDATED datetime DEFAULT NULL,
  UPDATED_BY bigint(20) DEFAULT NULL,
  PRIMARY KEY (EXP_MEASUREMENT_ID),
  KEY CATEGORY_ID (CATEGORY_ID),
  FOREIGN KEY (CATEGORY_ID) REFERENCES blc_category (CATEGORY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE broadleaf.ENC_MATERIAL_DESIGN_MAPPING (
   MATERIAL_DESIGN_MAPPING_ID   bigint(20)  NOT NULL,
   ORDER_ITEM_ID   bigint(20)  NOT NULL,
   REL_ORDER_ITEM_ID   bigint(20)  NOT NULL,
   QUANTITY  int(11) NOT NULL,   
   PRIMARY KEY (MATERIAL_DESIGN_MAPPING_ID),
   FOREIGN KEY (ORDER_ITEM_ID) REFERENCES blc_order_item(ORDER_ITEM_ID),
   FOREIGN KEY (REL_ORDER_ITEM_ID) REFERENCES blc_order_item(ORDER_ITEM_ID)
) ENGINE = InnoDB ROW_FORMAT = DEFAULT;



CREATE TABLE broadleaf.ENC_USER_CATEGORY (
   USER_CATEGORY_ID  bigint(20)  NOT NULL,
   USER_CATEGORY_NAME VARCHAR(20) NOT NULL,
   USER_CATEGORY_DESCRIPTION VARCHAR(100),
   CREATED_BY bigint(20) DEFAULT NULL,
   DATE_CREATED datetime DEFAULT NULL,
   DATE_UPDATED datetime DEFAULT NULL,
   UPDATED_BY bigint(20) DEFAULT NULL,
   END_DATE datetime DEFAULT NULL,
   PRIMARY KEY (USER_CATEGORY_ID)
   
) ENGINE = InnoDB ROW_FORMAT = DEFAULT;



CREATE TABLE broadleaf.ENC_SERVICE_PROVIDER (
   SP_ID  bigint(20)  NOT NULL,
   SP_FIRST_NAME VARCHAR(20) DEFAULT NULL,
   SP_LAST_NAME VARCHAR(20) DEFAULT NULL,
   SP_FIRM_NAME VARCHAR(20) DEFAULT NULL,
   SP_SHORT_DESCRIPTION VARCHAR(100),
   SP_LONG_DESCRIPTION VARCHAR(100),
   ADDRESS_ID bigint(20) DEFAULT NULL,
   CHALLENGE_QUESTION_ID bigint(20) DEFAULT NULL,
   CHALLENGE_ANSWER varchar(255) DEFAULT NULL,
   USER_NAME varchar(255) NOT NULL,
   PASSWORD varchar(255) DEFAULT NULL,
   PASSWORD_CHANGE_REQUIRED tinyint(1) DEFAULT NULL,
   RECEIVE_EMAIL tinyint(1) DEFAULT NULL,
   IS_REGISTERED tinyint(1) DEFAULT NULL,
   ENCLOTHE_URL VARCHAR(100),
   MERCHANT_URL VARCHAR(100),
   CURRENT_CAPACITY bigint(20),
   USER_CATEGORY_ID  bigint(20) NOT NULL, 
   IMAGE_URL VARCHAR(100),
   LOGO_URL VARCHAR(100),
   CREATED_BY bigint(20) DEFAULT NULL,
   DATE_CREATED datetime DEFAULT NULL,
   DATE_UPDATED datetime DEFAULT NULL,
   UPDATED_BY bigint(20) DEFAULT NULL,
   END_DATE datetime DEFAULT NULL,
   LOCALE_CODE varchar(255) DEFAULT NULL,
   PRIMARY KEY (SP_ID),
   FOREIGN KEY (USER_CATEGORY_ID) REFERENCES ENC_USER_CATEGORY (USER_CATEGORY_ID),
   FOREIGN KEY (ADDRESS_ID) REFERENCES blc_address (ADDRESS_ID),
   FOREIGN KEY (CHALLENGE_QUESTION_ID) REFERENCES blc_challenge_question (QUESTION_ID),
   FOREIGN KEY (LOCALE_CODE) REFERENCES blc_locale (LOCALE_CODE),
   UNIQUE (USER_NAME)
) ENGINE = InnoDB ROW_FORMAT = DEFAULT;


CREATE TABLE ENC_SERVICE_PROVIDER_FEATURED (
  FEATURED_SP_ID bigint(20) NOT NULL,
  PROMOTION_MESSAGE varchar(255) DEFAULT NULL,
  SEQUENCE bigint(20) DEFAULT NULL,
  SP_ID bigint(20) NOT NULL,
  PRIMARY KEY (FEATURED_SP_ID),
  FOREIGN KEY (SP_ID) REFERENCES ENC_SERVICE_PROVIDER (SP_ID)  
) ENGINE=InnoDB ROW_FORMAT = DEFAULT;

CREATE TABLE ENC_SERVICE_PROVIDER_ATTRIBUTE (
  SP_ATTRIBUTE_ID bigint(20) NOT NULL,
  NAME varchar(255) NOT NULL,
  SEARCHABLE tinyint(1) DEFAULT NULL,
  VALUE varchar(255) DEFAULT NULL,
  SP_ID bigint(20) NOT NULL,
  PRIMARY KEY (SP_ATTRIBUTE_ID),
  KEY SPATTRIBUTE_NAME_INDEX (NAME),
  KEY SPATTRIBUTE_INDEX (SP_ID),
  FOREIGN KEY (SP_ID) REFERENCES ENC_SERVICE_PROVIDER (SP_ID)
) ENGINE=InnoDB ROW_FORMAT = DEFAULT;

CREATE TABLE ENC_SERVICE_PROVIDER_ACCOUNT_INFO (
  SP_ACCOUNT_INFO_ID bigint(20) NOT NULL,
  ACCOUNT_HOLDER_NAME varchar(255),
  BANK_NAME varchar(255),
  BANK_IFSC_CODE varchar(255),
  ACCOUNT_NO varchar(255),
  BRANCH varchar(255),
  BANK_ADDRESS_ID bigint(20) DEFAULT NULL,
  ACCOUNT_TYPE varchar(255),
  CREATED_BY bigint(20) DEFAULT NULL,
  DATE_CREATED datetime DEFAULT NULL,
  DATE_UPDATED datetime DEFAULT NULL,
  UPDATED_BY bigint(20) DEFAULT NULL,
  END_DATE datetime DEFAULT NULL,  
  SP_ID bigint(20) NOT NULL,
  PRIMARY KEY (SP_ACCOUNT_INFO_ID),
  FOREIGN KEY (SP_ID) REFERENCES ENC_SERVICE_PROVIDER (SP_ID),
  FOREIGN KEY (BANK_ADDRESS_ID) REFERENCES blc_address (ADDRESS_ID)
) ENGINE=InnoDB ROW_FORMAT = DEFAULT;

CREATE TABLE broadleaf.ENC_DISPUTE_STATES (
	DISPUTE_STATE_ID bigint(20)  NOT NULL,
	DISPUTE_STATE_NAME varchar(255) NOT NULL,
	DISPUTE_STATE_SHORT_DESC varchar(100) ,
	DISPUTE_STATE_LONG_DESC varchar(255) ,
	CREATED_BY bigint(20) DEFAULT NULL,
	DATE_CREATED datetime DEFAULT NULL,
	DATE_UPDATED datetime DEFAULT NULL,
	UPDATED_BY bigint(20) DEFAULT NULL,
   	END_DATE datetime DEFAULT NULL,
   	PRIMARY KEY (DISPUTE_STATE_ID)
   	) ENGINE = InnoDB ROW_FORMAT = DEFAULT;

CREATE TABLE broadleaf.ENC_DISPUTE_PRIORITY (
	DISPUTE_PRIORITY_ID bigint(20)  NOT NULL,
	DISPUTE_PRIORITY_NAME varchar(255) NOT NULL,
	DISPUTE_PRIORITY_SHORT_DESC varchar(100)  ,
	DISPUTE_PRIORITY_LONG_DESC varchar(255)  ,	
    CREATED_BY bigint(20) DEFAULT NULL,
    DATE_CREATED datetime DEFAULT NULL,
    DATE_UPDATED datetime DEFAULT NULL,
    UPDATED_BY bigint(20) DEFAULT NULL,
   	END_DATE datetime DEFAULT NULL,
   	PRIMARY KEY (DISPUTE_PRIORITY_ID)
   	) ENGINE = InnoDB ROW_FORMAT = DEFAULT;
   	
   	
CREATE TABLE broadleaf.ENC_DISPUTE_CHANNEL (   	
	DISPUTE_CHANNEL_ID bigint(20)  NOT NULL,
	DISPUTE_CHANNEL_NAME varchar(255) NOT NULL,
	DISPUTE_CHANNEL_SHORT_DESC varchar(100)  ,
	DISPUTE_CHANNEL_LONG_DESC varchar(255)  ,	
	CREATED_BY bigint(20) DEFAULT NULL,
   	DATE_CREATED datetime DEFAULT NULL,
   	END_DATE datetime DEFAULT NULL,
   	PRIMARY KEY (DISPUTE_CHANNEL_ID)
   	) ENGINE = InnoDB ROW_FORMAT = DEFAULT;



CREATE TABLE broadleaf.ENC_DISPUTE (
   DISPUTE_ID   bigint(20)  NOT NULL,
   ORDER_ITEM_ID   bigint(20)  NOT NULL,
   DISPUTE_SP_ID   bigint(20)  NOT NULL,
   CUSTOMER_ID   bigint(20)  NOT NULL,
   DISPUTE_STATE_ID   bigint(20)  NOT NULL,
   DISPUTE_PRIORITY_ID   bigint(20)  NOT NULL,
   DISPUTE_CHANNEL_ID bigint(20)  DEFAULT NULL,
   CREATED_BY bigint(20) DEFAULT NULL,
   DATE_CREATED datetime DEFAULT NULL,
   DATE_UPDATED datetime DEFAULT NULL,
   UPDATED_BY bigint(20) DEFAULT NULL,
   END_DATE datetime DEFAULT NULL,
   PRIMARY KEY (DISPUTE_ID),
   FOREIGN KEY (ORDER_ITEM_ID) REFERENCES blc_order_item(ORDER_ITEM_ID),
   FOREIGN KEY (DISPUTE_SP_ID) REFERENCES ENC_SERVICE_PROVIDER(SP_ID),
   FOREIGN KEY (CUSTOMER_ID) REFERENCES blc_customer(CUSTOMER_ID),
   FOREIGN KEY (DISPUTE_STATE_ID) REFERENCES ENC_DISPUTE_STATES(DISPUTE_STATE_ID),
   FOREIGN KEY (DISPUTE_PRIORITY_ID) REFERENCES ENC_DISPUTE_PRIORITY(DISPUTE_PRIORITY_ID),
   FOREIGN KEY (DISPUTE_CHANNEL_ID) REFERENCES ENC_DISPUTE_CHANNEL(DISPUTE_CHANNEL_ID)
) ENGINE = InnoDB ROW_FORMAT = DEFAULT;

CREATE TABLE broadleaf.ENC_DISPUTE_COMMENTS (
    DISPUTE_COMMENTS_ID bigint(20)  NOT NULL,
    DISPUTE_ID bigint(20)  NOT NULL,
    COMMENTS varchar(500) NOT NULL,
    DISPUTE_CHANNEL_ID bigint(20)  DEFAULT NULL,
    CREATED_BY bigint(20) DEFAULT NULL,
    DATE_CREATED datetime DEFAULT NULL,
    DATE_UPDATED datetime DEFAULT NULL,
    UPDATED_BY bigint(20) DEFAULT NULL,
    PRIMARY KEY (DISPUTE_COMMENTS_ID),
    FOREIGN KEY (DISPUTE_ID) REFERENCES ENC_DISPUTE(DISPUTE_ID),
    FOREIGN KEY (DISPUTE_CHANNEL_ID) REFERENCES ENC_DISPUTE_CHANNEL(DISPUTE_CHANNEL_ID)
    ) ENGINE = InnoDB ROW_FORMAT = DEFAULT;


CREATE TABLE broadleaf.ENC_DISPUTE_STATE_TRANSITION (
    DISPUTE_STATE_TRANSITION_ID bigint(20)  NOT NULL,
    DISPUTE_ID bigint(20)  NOT NULL,
    DISPUTE_STATE_ID bigint(20)  NOT NULL,
    DISPUTE_CHANNEL_ID bigint(20)  DEFAULT NULL,
    CREATED_BY bigint(20) DEFAULT NULL,
    DATE_CREATED datetime DEFAULT NULL,
    DATE_UPDATED datetime DEFAULT NULL,
    UPDATED_BY bigint(20) DEFAULT NULL,
    PRIMARY KEY (DISPUTE_STATE_TRANSITION_ID),
    FOREIGN KEY (DISPUTE_ID) REFERENCES ENC_DISPUTE(DISPUTE_ID),
    FOREIGN KEY (DISPUTE_STATE_ID) REFERENCES ENC_DISPUTE_STATES(DISPUTE_STATE_ID),
    FOREIGN KEY (DISPUTE_CHANNEL_ID) REFERENCES ENC_DISPUTE_CHANNEL(DISPUTE_CHANNEL_ID)
    ) ENGINE = InnoDB ROW_FORMAT = DEFAULT;

CREATE TABLE broadleaf.ENC_ORDER_STATES (
	ORDER_STATE_ID bigint(20)  NOT NULL,
	ORDER_STATE_NAME varchar(255) NOT NULL,
	ORDER_STATE_SHORT_DESC varchar(100) ,
	ORDER_STATE_LONG_DESC varchar(255) ,
    CREATED_BY bigint(20) DEFAULT NULL,
    DATE_CREATED datetime DEFAULT NULL,
    DATE_UPDATED datetime DEFAULT NULL,
    UPDATED_BY bigint(20) DEFAULT NULL,
   	END_DATE datetime DEFAULT NULL,
   	PRIMARY KEY (ORDER_STATE_ID)   	
   	) ENGINE = InnoDB ROW_FORMAT = DEFAULT;
   	
   	
CREATE TABLE broadleaf.ENC_ORDER_DETAIL (
	   ORDER_DETAIL_ID bigint(20)  NOT NULL,
	   CURRENT_OWNER bigint(20)  NOT NULL,
	   OWNER_CATEGORY_ID  bigint(20)  NOT NULL,
	   ORDER_ITEM_ID  bigint(20)  NOT NULL,
	   CURRENT_STATE_ID bigint(20)  NOT NULL,
	   EXPECTED_DELIVERY_DATE datetime DEFAULT NULL,
	   PRIMARY KEY (ORDER_DETAIL_ID), 	
	   FOREIGN KEY (OWNER_CATEGORY_ID) REFERENCES ENC_USER_CATEGORY(USER_CATEGORY_ID),
	   FOREIGN KEY (ORDER_ITEM_ID) REFERENCES blc_order_item(ORDER_ITEM_ID),
	   FOREIGN KEY (CURRENT_STATE_ID) REFERENCES ENC_ORDER_STATES(ORDER_STATE_ID)
   	) ENGINE = InnoDB ROW_FORMAT = DEFAULT;


CREATE TABLE broadleaf.ENC_ORDER_STATE_TRANSITION (
    ORDER_STATE_TRANSITION_ID bigint(20)  NOT NULL,
    ORDER_ITEM_ID bigint(20)  NOT NULL,
    ORDER_STATE_ID bigint(20)  NOT NULL,
    NEW_OWNER bigint(20),
    NEW_OWNER_CATEGORY_ID  bigint(20),
    PREV_OWNER bigint(20),
    PREV_OWNER_CATEGORY_ID  bigint(20),
    COMMENTS varchar(500),
    CREATED_BY bigint(20) DEFAULT NULL,
    DATE_CREATED datetime DEFAULT NULL,
    DATE_UPDATED datetime DEFAULT NULL,
    UPDATED_BY bigint(20) DEFAULT NULL,
    PRIMARY KEY (ORDER_STATE_TRANSITION_ID),
    FOREIGN KEY (ORDER_ITEM_ID) REFERENCES blc_order_item(ORDER_ITEM_ID),
    FOREIGN KEY (ORDER_STATE_ID) REFERENCES ENC_ORDER_STATES(ORDER_STATE_ID),
    FOREIGN KEY (NEW_OWNER_CATEGORY_ID) REFERENCES ENC_USER_CATEGORY(USER_CATEGORY_ID),
    FOREIGN KEY (PREV_OWNER_CATEGORY_ID) REFERENCES ENC_USER_CATEGORY(USER_CATEGORY_ID)
    ) ENGINE = InnoDB ROW_FORMAT = DEFAULT;